sudo: required
services: 
    - docker

before_install:
    - docker build -t vish0309/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vish0309/react-test npm test

after_success:
    -docker build -t vish0309/multi-client ./client
    -docker build -t vish0309/multi-nginx ./nginx
    -docker build -t vish0309/multi-server ./server
    -docker build -t vish0309/multi-worker ./worker
    
    -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push vish0309/multi-client
    - docker push vish0309/multi-nginx
    - docker push vish0309/multi-server
    - docker push vish0309/multi-worker
